### ISSUE TITLE
BUG: missing file

### ISSUE THREAD

**Issue by mathurinm** [allambert/torch_itl#7]
trying to run the missing_data.py demo:
```OSError: ../../torch_itl/datasets/KDEF_Aligned/KDEF_LANDMARKS/AF01ANS.txt not found.```
if it's light we can commit it, otherwise you need a fetcher with the `download` module for example

**Comment by mathurinm** [comment]
ah, an accreditation is needed to get the data. do you think a workaround is possible ?

**Comment by allambert** [comment]
That's because we do not have the rights over the kdef dataset. Therefore to run the scripts in demo/emotion_transfer you need first to download the dataset (also another dataset called RaFD) and apply the script demo/emotion_transfer/utils/face_aligner.py. We tried to explain it in the corresponding README

**Comment by allambert** [comment]
No I don't think so. It makes the demo a bit complicated to use I agree, but I don't see how we can do otherwise.

**Comment by mathurinm** [comment]
I see. It's clear in the readme.
IMO it'd be nice to create a fetch_kdef() function which raises an error message with a pointer if data is not present ("data folder appears to be empty, request download  from this url etc")

**Comment by allambert** [comment]
Ok, I'll modify the get_data_landmarks() in torch_itl.datasets to raise an error message if the path in arguments does not lead to the data, and point to the corresponding dataset.

**Comment by allambert** [comment]
I've added a try block that catches OSError, closing the issue. Thanks for pointing this out.
